FakeAPI/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import re_path, include

from endpoint_manager.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='index'),
    path('novoendpoint', novo_endpoint),
    path('removerendpoints', remover_endpoints),
    re_path(r'api/.+', endpoint_retorno),
]

endpoint_manager/models.py
from datetime import datetime
from operator import mod
from pyexpat import model
from django.db import models
from enum import Enum

# Create your models here.

class MetodosRequisicao(Enum):
	GET = 'GET'
	POST = 'POST'
	PUT = 'PUT'
	DELETE = 'DELETE'
	PATCH = 'PATCH'

class RetornosRequisicao(Enum):
	JSON = 'JSON'
	XML = 'XML'

class Endpoint(models.Model):
	METODOS_REQUISICAO = (
		('GET', MetodosRequisicao.GET.value),
		('POST', MetodosRequisicao.POST.value),
		('PUT', MetodosRequisicao.PUT.value),
		('DELETE', MetodosRequisicao.DELETE.value),
		('PATCH', MetodosRequisicao.PATCH.value)
	)

	TIPO_RETORNO = (
		('JSON', RetornosRequisicao.JSON.value),
		('XML', RetornosRequisicao.XML.value)
	)

	base_route = models.CharField(max_length=50)
	endpoint = models.CharField(max_length=90, default='')
	status_code = models.IntegerField(default=200)
	metodo_http = models.CharField(max_length=10, choices=METODOS_REQUISICAO, default=MetodosRequisicao.GET.value)
	tipo_retorno = models.CharField(max_length=10, choices=TIPO_RETORNO, default=RetornosRequisicao.JSON.value)
	retorno = models.TextField()
	created_at = models.DateTimeField(auto_now_add=True, blank=True)

endpoint_manager/forms.py
from django import forms
from .models import Endpoint

class EndpointForm(forms.ModelForm):
	class Meta:
		model = Endpoint
		fields = ['endpoint', 'status_code', 'metodo_http', 'tipo_retorno', 'retorno']

endpoint_manager/views.py
from datetime import datetime, timedelta
from django.conf import settings
from django.shortcuts import render, redirect
from .models import *
from django.db.models import Q
from .forms import EndpointForm
from django.contrib import messages
import uuid
from django.http import HttpResponseForbidden, HttpResponseNotFound, HttpResponse
from django.views.decorators.csrf import csrf_exempt
import pdb
import json

# Create your views here.
def home(request):
	remover_endpoints_antigos()

	data = {}
	data['base_route'] = genarate_base_route(request)
	data['site_url'] = settings.SITE_URL

	endpoints = Endpoint.objects.filter(base_route=data['base_route'])
	data['endpoints'] = endpoints

	return render(request, 'endpoint_manager/home.html', data)

def remover_endpoints_antigos():
	hoje = datetime.now().date()
	dataAntiga = hoje - timedelta(7)
	objects = Endpoint.objects.filter(Q(created_at__lt=dataAntiga) | Q(created_at__isnull=True))
	objects.delete()

@csrf_exempt
def endpoint_retorno(request):
	paths = request.get_full_path().split('/')
	del paths[0]
	del paths[0]

	base_url_request = paths[0]
	del paths[0]

	endpoint_request = '/'.join(paths)

	endpoint = Endpoint.objects.filter(
		endpoint=endpoint_request,
		base_route=base_url_request,
		metodo_http=request.method
	).first()

	if not endpoint:
		return HttpResponseNotFound()

	content_type_result = 'application/json'
	if endpoint.tipo_retorno == RetornosRequisicao.XML.value:
		content_type_result = 'application/xml'

	return HttpResponse(endpoint.retorno, content_type=content_type_result, status=endpoint.status_code)

def remover_endpoints(request):
	if 'base_route' not in request.session:
		messages.error(request, 'Erro na busca de endpoints', extra_tags='danger')
		return redirect('/')

	if request.GET.get('id'):
		objects = Endpoint.objects.filter(base_route=request.session['base_route'], id=request.GET.get('id'))
	else:
		objects = Endpoint.objects.filter(base_route=request.session['base_route'])

	objects_number = objects.count()

	if objects_number <= 0:
		messages.error(request, 'Não há endpoints para excluir', extra_tags='danger')
		return redirect('/')

	objects.delete()
	messages.success(request, 'Endpoint(s) excluído(s) com sucesso')
	return redirect('/')

def novo_endpoint(request):
	data = {}

	form = EndpointForm(request.POST or None)
	if form.is_valid():
		form.instance.base_route = genarate_base_route(request)
		form.save()
		messages.success(request, 'Endpoint cadastrado com sucesso')
		return redirect('/')

	data['form'] = form

	return render(request, 'endpoint_manager/novoendpoint_pagina.html', data)

def genarate_base_route(request):
	if 'base_route' not in request.session:
		request.session['base_route'] = uuid_generator()

	# Pega o valor da sessão, seta o valor da chave como padrão se  não estiver presente.
	return request.session['base_route']

def uuid_generator(string_length=10):
	"""Returns a random string of length string_length."""
	random = str(uuid.uuid4()) # Convert UUID format to a Python string.
	random = random.upper() # Make all characters uppercase.
	random = random.replace("-","") # Remove the UUID '-'.
	return random[0:string_length] # Return the random string.

endpoint_manager/templates/endpoint_manager/head.html
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
	<title>Fake API</title>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js" integrity="sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
</head>

endpoint_manager/templates/endpoint_manager/home.html
<!DOCTYPE html>
<html>
{% include "endpoint_manager/head.html" %}
<body class="bg-light">
	<div class="container mt-4 text-center bg-white p-4 rounded-3 shadow">
		<h1>FakeApi</h1>
		<input type="text" class="form-control text-center" id="base_route" value="{{site_url}}/api/{{base_route}}" readonly>
	</div>    

	{% if messages %}
		<div class="container mt-4">
			{% for message in messages %}
				<div class="alert {% if message.tags %} alert-{{ message.tags }} {% endif %} alert-dismissible fade show" role="alert">
					<span>
						{{ message }}
					</span>
					<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
				</div>
			{% endfor %}
		</div>
	{% endif %}
	
	<div class="container mt-2 p-4">
		<div class="d-flex justify-content-between align-items-center mb-4">
			<h3>Endpoints</h3>
			<div>
				<a href="/removerendpoints" class="btn btn-sm btn-danger"><i class="fa-solid fa-trash-can"></i> Remover tudo</a>
				<a href="/novoendpoint" class="btn btn-sm btn-success"><i class="fa-solid fa-plus"></i> Novo Endpoint</a>
			</div>
		</div>
		<div>
			<div class="accordion" id="accordionPanel">
				{% if endpoints %}
					{% for endpoint in endpoints %}
						<div class="accordion-item">
							<h2 class="accordion-header" id="panelsEndpoint-{{ endpoint.id }}">
								<div class="accordion-button collapsed p-2" data-bs-toggle="collapse" data-bs-target="#panelsCalapseEndpoint-{{ endpoint.id }}" aria-expanded="false" aria-controls="panelsCalapseEndpoint-{{ endpoint.id }}">
									<div class="d-flex justify-content-between flex-wrap w-100">
										<div class="d-flex align-items-centergap-2">
											<div class="d-flex align-items-center gap-2">
												<div>
													<button style="font-size: 14px; width: 100px" class="btn btn-sm px-2 py-0 mt-1 btn-primary">
														{{ endpoint.metodo_http }}
													</button>             
												</div>
												<p class="p-0 m-0 fw-bold text-secondary" style="font-size: 14px">/{{ endpoint.endpoint }}</p>
											</div>
										</div>
										<div class="px-4">
											<button onclick="copy('{{site_url}}/api/{{base_route}}/{{endpoint.endpoint}}')" class="btn btn-outline-secondary"><i class="fa-solid fa-copy"></i></button>
											<a href="/removerendpoints?id={{ endpoint.id }}" class="btn btn-sm btn-danger"><i class="fa-solid fa-trash-can"></i></a>
										</div>
									</div>
								</div>
							</h2>
							<div id="panelsCalapseEndpoint-{{ endpoint.id }}" class="accordion-collapse collapse" aria-labelledby="panelsEndpoint-{{ endpoint.id }}">
								<div class="accordion-body">
									<label for="Resposta" class="form-label">Retorno ({{ endpoint.status_code }})</label>
									<textarea class="form-control" id="Resposta" rows="3" readonly>{{ endpoint.retorno }}</textarea>
								</div>
							</div>
						</div>
					{% endfor %}
				{% endif %}
			</div>
		</div>
	</div>

	<script>
		function copy(text) {
			var input = document.createElement('input');
			
			input.setAttribute('value', text);
			document.body.appendChild(input);
			input.select();
			
			var result = document.execCommand('copy');
			document.body.removeChild(input)
			
			alert('Copiado');
			return result;
	}
	</script>

	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>
</html>

endpoint_manager/templates/endpoint_manager/novoendpoint_pagina.html
<html>

{% include "endpoint_manager/head.html" %}
<body class="bg-light">
    {% if form.errors %}
        <div class="alert alert-danger">
            {{ form.errors }}
        </div>
    {% endif %}
    <div class="container mt-4 mb-4 bg-white p-4 rounded-3 shadow">
        <div style="max-width: 480px;margin: auto;">
            <div class="d-flex flex-wrap justify-content-between align-items-center">
                <div>
                    <a href="/" class="btn btn-light">
                        <i class="fa-solid fa-arrow-left"></i>
                        Voltar
                    </a>
                </div>
                <h1 class="text-center mt-2 mb-2">Novo Endpoint</h1>
            </div>
            
            <div>
                <form method="POST">
                    {% csrf_token %}
                    <div class="row">
                        {% for field in form %}
                        <div class="col-12">
                            <div class="mb-3">
                                <div><label for="id_{{ field.name }}" class="form-label">{{ field.label }}</label></div>
                                {{ field }} 
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                    
                    <div class="mb-3">
                        <button type="submit" class="btn btn-primary w-100">
                            <i class="fa-solid fa-floppy-disk"></i>
                            Salvar
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
   
    <script>
        
        $('input, textarea, select').addClass('form-control');
        $('#id_endpoint').on('input', function () {
            let endpoint = $('#id_endpoint').val()
            let primeiroCaractere =  endpoint.charAt(0)
            
            if (primeiroCaractere == '/') {
                endpoint = endpoint.substring(1)
            }

            $('#id_endpoint').val(endpoint)
        })
    </script>

</body>
</html>